# ??????? ??????????? Logbook
logging.level.org.zalando.logbook=TRACE

# ???????? ?????? ???????? ? ???????
logbook.write-requests=true
logbook.write-responses=true

# ??????????? ????? ? JSON (?????? ??? ??????)
logbook.format.style=json

# ???? ?????, ????? ???????? ???????????? ???????????????? ??????
# logbook.filter.enabled=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

# TODO Append connection to Postgres DB

spring.datasource.url=jdbc:h2:file:./db/shareit
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG
